name: testbuildexternal

on:
  workflow_dispatch:
  push:
  pull_request:
  check_run:
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.5
      with:
          owner: Tygozwolle
          repo: rpi-system-sensors-docker
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: main.yml
          ref: Test
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          comment_downstream_url: ${{ github.event.pull_request.comments_url }}
